name: Lint HTML and CSS

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Linting Tools
      run: |
        npm install htmlhint stylelint

    - name: Lint HTML Files
      run: npx htmlhint "src/homePage.html"
         

    - name: Lint CSS Files
      run: npx stylelint "styles/homePageStyle.css"
